version: '3'

services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/kkkstra/ngb:latest
    ports:
      - "8111:8111"
    depends_on:
      - db
      - redis
    networks:
      - ngb
    volumes:
      - "./log:/var/log"
    restart: always

  db:
    image: postgres:15
    expose:
      - "5432"
    networks:
      - ngb
    environment:
      POSTGRES_DB: ngb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "/data/redis/redis.conf:/etc/redis/redis.conf"
      - "/data/redis/data:/data"
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    networks:
      - ngb
    restart: always

networks:
  ngb:
    driver: bridge
