version: '3'

services:
  web:
    build: .
    ports:
      - "7777:7777"
    depends_on:
      - db
    networks:
      - ngb
    restart: always

  db:
    image: postgres:15
    expose:
      - "5432"
    networks:
      - ngb
    environment:
      POSTGRES_DB: ngb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    restart: always

networks:
  ngb:
    driver: bridge
