app:
  addr: ":7777"
postgresql:
  host: db
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "ngb"
debug:
  enable: false
init-env:
  admin: true
  rsa-key: false
user:
  user-jwt:
    expire: 168
    issuer: "kkkstra.cn"
  admin:
    username: "admin"
    password: "123456"
    email: "admin@admin.com"