app:
  addr: ":8111"
database:
  host: db
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "ngb"
debug:
  enable: false
user:
  jwt:
    expire: 168
    issuer: "ngb.kkkstra.cn"
    key: "kkkstra"
