name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: docker build -t ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}:latest .
    - name: Login to Registry # 登录阿里云镜像服务器
      run: docker login --username=${{ secrets.ALI_DOCKER_HUB_USERNAME }} --password=${{ secrets.ALI_DOCKER_HUB_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
    - name: Push Image # 推送镜像，设置版本为latest
      run: docker push ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}:latest
    - name: Setup SSH Private Key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.REMOTE_PRIVATE_KEY }}" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
    - name: Login to Server
      run: |
        ssh ${{ secrets.REMOTE_HOST_USERNAME }}@${{ secrets.REMOTE_HOST }}
        echo "just for test" >> test.txt
