name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: "${{ secrets.ALI_DOCKER_HUB_REGISTRY }}"
        username: "${{ secrets.ALI_DOCKER_HUB_USERNAME }}"
        password: "${{ secrets.ALI_DOCKER_HUB_PASSWORD }}"
    - name: Build Docker Image
      run: docker build -t ${{ secrets.ALI_DOCKER_HUB_REGISTRY }:latest .
    - name: Push Docker Image
      run: docker push ${{ secrets.ALI_DOCKER_HUB_REGISTRY }:latest
